version: "3.8"
services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./volumes/webserver-log:/var/log/nginx
    ports:
      - "8080:80"
  shipper:
    image: docker.elastic.co/beats/filebeat:7.16.2
    container_name: shipper
    user: root
    volumes:
      - ./config/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./volumes/webserver-log:/var/log/nginx

## Common-network
networks:
  default:
    external:
      name: elk-network
