metricbeat.config.modules:
  enabled: true
  reload.enabled: false
  reload.period: 10s
  path: ${path.config}/modules.d/*.yml

setup.dashboards.enabled: true
setup.kibana.host: kibana:5601

output.elasticsearch:
  hosts: ["es-master-1:9200"]

metricbeat.modules:
  - module: elasticsearch
    xpack.enabled: true
    period: 10s
    hosts:
      [
        "http://es-master-1:9200",
        "http://es-slave-1:9200",
        "http://es-slave-2:9200",
      ]
